import { Company, Task } from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Mundillantas',
    color: '#3b82f6', // Blue
    status: 'activa',
    notes: 'Cliente principal de neumáticos. Enfoque en conversión B2C y reconocimiento de marca.',
    managerName: 'Sofía Pasquel',
    managerEmail: 'sofia@mundillantas.com',
    teamName: 'Equipo de Diseño Mundillantas',
    teamEmail: 'carlos@igenius.com',
    allowedViewsCliente: ['calendario', 'kanban', 'colaboracion'],
    allowedViewsEquipo: ['calendario', 'kanban', 'roadmap', 'timeline', 'colaboracion']
  },
  {
    id: 'c2',
    name: 'Austrollantas',
    color: '#f97316', // Orange
    status: 'activa',
    notes: 'Distribuidor regional. Campañas de pauta localizadas y generación de leads comerciales.',
    managerName: 'Gerente Austrollantas',
    managerEmail: 'gerente@austrollantas.com',
    teamName: 'Equipo Técnico Austrollantas',
    teamEmail: 'equipo@austrollantas.com',
    allowedViewsCliente: ['calendario', 'kanban'],
    allowedViewsEquipo: ['calendario', 'kanban', 'roadmap']
  },
  {
    id: 'c3',
    name: 'CERFIK',
    color: '#10b981', // Emerald
    status: 'activa',
    notes: 'Centro de capacitación y formación profesional. CRM automation y lanzamientos de cursos.',
    managerName: 'Director CERFIK',
    managerEmail: 'director@cerfik.com',
    teamName: 'Equipo CERFIK',
    teamEmail: 'equipo@cerfik.com',
    allowedViewsCliente: ['calendario', 'kanban'],
    allowedViewsEquipo: ['calendario', 'kanban', 'roadmap', 'timeline']
  },
  {
    id: 'c4',
    name: 'IEBI',
    color: '#8b5cf6', // Violet
    status: 'activa',
    notes: 'Instituto de educación básica integral. Posicionamiento SEO y captación de matrículas.',
    managerName: 'Rector IEBI',
    managerEmail: 'rector@iebi.com',
    teamName: 'Equipo IEBI',
    teamEmail: 'equipo@iebi.com',
    allowedViewsCliente: ['calendario', 'roadmap'],
    allowedViewsEquipo: ['calendario', 'kanban', 'roadmap', 'timeline']
  },
  {
    id: 'c5',
    name: 'Tecnidiesel Pasquel',
    color: '#ef4444', // Red
    status: 'activa',
    notes: 'Taller especializado diesel. Campañas de video en YouTube y pauta en Google Maps.',
    managerName: 'Gerente Pasquel',
    managerEmail: 'gerente@tecnidiesel.com',
    teamName: 'Equipo Tecnidiesel',
    teamEmail: 'equipo@tecnidiesel.com',
    allowedViewsCliente: ['calendario', 'kanban'],
    allowedViewsEquipo: ['calendario', 'kanban', 'roadmap', 'timeline']
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't1',
    companyId: 'c1',
    title: 'Plan de Contenidos - Instagram & Facebook',
    description: 'Estructurar la parrilla de contenidos mensual bajo la metodología Growth Scaling, enfocada en enganchar leads y educar sobre seguridad vial.',
    type: 'Contenido',
    startDate: '2026-07-02',
    endDate: '2026-07-10',
    status: 'Completado',
    priority: 'Alta',
    checklist: [
      { id: 'sub-1', text: 'Investigación de tendencias y dolores del cliente', completed: true },
      { id: 'sub-2', text: 'Redacción de copys en hoja de trabajo', completed: true },
      { id: 'sub-3', text: 'Diseño de carruseles y reels en Canva', completed: true },
      { id: 'sub-4', text: 'Aprobación del cliente y programación en Meta Business', completed: true },
    ],
    progress: 100,
  },
  {
    id: 't2',
    companyId: 'c2',
    title: 'Estructura Campaña Google Ads (Llantas de Invierno)',
    description: 'Lanzamiento de campaña de búsqueda de Google Ads enfocada en conversión directa para tiendas locales de neumáticos.',
    type: 'Pauta',
    startDate: '2026-07-10',
    endDate: '2026-07-18',
    status: 'En proceso',
    priority: 'Alta',
    checklist: [
      { id: 'sub-5', text: 'Estudio de palabras clave de alta intención de compra', completed: true },
      { id: 'sub-6', text: 'Crear variaciones de títulos y descripciones persuasivas', completed: true },
      { id: 'sub-7', text: 'Configurar extensiones de llamada y ubicación', completed: false },
      { id: 'sub-8', text: 'Establecer pujas automatizadas y presupuesto diario', completed: false },
    ],
    progress: 50,
  },
  {
    id: 't3',
    companyId: 'c3',
    title: 'Flujo de Email Marketing Automatizado (Bienvenida)',
    description: 'Diseñar e implementar la secuencia de correos automáticos para nuevos prospectos que se registran en los webinars gratuitos de CERFIK.',
    type: 'CRM',
    startDate: '2026-07-06',
    endDate: '2026-07-13',
    status: 'En revisión',
    priority: 'Media',
    checklist: [
      { id: 'sub-9', text: 'Redacción de los 3 correos de la secuencia', completed: true },
      { id: 'sub-10', text: 'Maquetar plantillas con branding de CERFIK', completed: true },
      { id: 'sub-11', text: 'Configurar disparadores de registro en ActiveCampaign', completed: true },
      { id: 'sub-12', text: 'Prueba de envío y corrección de enlaces rotos', completed: false },
    ],
    progress: 75,
  },
  {
    id: 't4',
    companyId: 'c4',
    title: 'Reunión de Resultados de Campaña Q2',
    description: 'Sesión estratégica por Zoom para presentar el informe de conversiones, costo por lead (CPL) y retorno de inversión en pauta educativa.',
    type: 'Reunión',
    startDate: '2026-07-13',
    endDate: '2026-07-13',
    status: 'Por hacer',
    priority: 'Alta',
    checklist: [
      { id: 'sub-13', text: 'Consolidar datos de Google & Meta Ads', completed: true },
      { id: 'sub-14', text: 'Crear diapositivas del reporte en Google Slides', completed: false },
      { id: 'sub-15', text: 'Enviar invitación del calendario con enlace de Zoom', completed: false },
    ],
    progress: 33,
  },
  {
    id: 't5',
    companyId: 'c5',
    title: 'Auditoría SEO Técnica & On-Page',
    description: 'Revisión exhaustiva del sitio web de Tecnidiesel Pasquel para detectar enlaces rotos, velocidad lenta y optimizar las palabras clave locales.',
    type: 'Entrega',
    startDate: '2026-07-15',
    endDate: '2026-07-22',
    status: 'Por hacer',
    priority: 'Alta',
    checklist: [
      { id: 'sub-16', text: 'Análisis de rastreo con Screaming Frog', completed: false },
      { id: 'sub-17', text: 'Auditoría de Core Web Vitals y velocidad móvil', completed: false },
      { id: 'sub-18', text: 'Optimización de metatítulos y meta descripciones h1/h2', completed: false },
      { id: 'sub-19', text: 'Crear reporte final con sugerencias de desarrollo', completed: false },
    ],
    progress: 0,
  },
  {
    id: 't6',
    companyId: 'c1',
    title: 'Reporte Quincenal de Rendimiento de Pauta',
    description: 'Revisión de métricas de Facebook Ads de la quincena. Ajustes de pujas, públicos y exclusión de leads no calificados.',
    type: 'Administrativo',
    startDate: '2026-07-14',
    endDate: '2026-07-16',
    status: 'Por hacer',
    priority: 'Media',
    checklist: [],
    progress: 0,
  },
  {
    id: 't7',
    companyId: 'c3',
    title: 'Optimización de Landing Page de Curso de Growth Scaling',
    description: 'Implementar mejoras de copywriting y diseño basadas en mapas de calor para aumentar la conversión de visitas a prospectos registrados.',
    type: 'Entrega',
    startDate: '2026-07-01',
    endDate: '2026-07-06',
    status: 'Completado',
    priority: 'Alta',
    checklist: [
      { id: 'sub-20', text: 'Analizar grabaciones de usuarios con Hotjar', completed: true },
      { id: 'sub-21', text: 'Reescribir propuesta de valor del encabezado', completed: true },
      { id: 'sub-22', text: 'Hacer el botón CTA flotante en versión móvil', completed: true },
    ],
    progress: 100,
  },
  {
    id: 't8',
    companyId: 'c2',
    title: 'Diseño de Piezas Gráficas para Campaña de Liquidación',
    description: 'Creación de recursos visuales y adaptaciones de tamaño (feed, stories, horizontal) para la campaña relámpago de liquidación de stock de neumáticos.',
    type: 'Contenido',
    startDate: '2026-07-20',
    endDate: '2026-07-25',
    status: 'Por hacer',
    priority: 'Baja',
    checklist: [
      { id: 'sub-23', text: 'Redactar las ideas de diseño y directrices de marca', completed: false },
      { id: 'sub-24', text: 'Diseñar 3 piezas estáticas y 1 plantilla para historias', completed: false },
    ],
    progress: 0,
  },
  {
    id: 't9',
    companyId: 'c4',
    title: 'Configuración de Pixel de Conversión de TikTok',
    description: 'Instalación y testeo de eventos del Pixel de TikTok en el sitio de admisiones para medir registros directos provenientes de campañas de video corto.',
    type: 'Pauta',
    startDate: '2026-07-05',
    endDate: '2026-07-08',
    status: 'Completado',
    priority: 'Media',
    checklist: [
      { id: 'sub-25', text: 'Crear pixel en el centro de negocios de TikTok', completed: true },
      { id: 'sub-26', text: 'Instalar fragmento de código a través de GTM', completed: true },
      { id: 'sub-27', text: 'Verificar disparo de eventos de registro completo', completed: true },
    ],
    progress: 100,
  },
];
